services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  server:
    image: nginx:latest
    container_name: server
    ports:
      - "8876:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
